FROM node:18-alpine as build

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

# Run tests if TEST_E2E environment variable is set
ARG TEST_E2E=false
RUN if [ "$TEST_E2E" = "true" ] ; then npm run test:e2e ; fi

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 